### ISSUE TITLE
Регистрация зависимости Commands.Move в IoC.

### ISSUE THREAD

**Issue by coloures** [coloures/SpaceBattleGameWithTests#22]
Зарегистрировать зависимость "Commands.Move" в IoC, с помощью которой можно разрешить команду MoveCommand по игровому объекту. Для регистрации зависимости определит отдельную команду с префиксом RegisterIoCDependency.
Примечание: Для того, чтобы создать MoveCommand, необходимо создать адаптер IDictionary<string, object> для интерфейса IMovingObject. Задача конструирования Адаптеров по интерфейсу будет рассмотрена в другой лабораторной работе, поэтому в данной задаче используйте разрешение зависимости Ioc.Resolve("Adapters.IMovingObject", obj), где obj - игровой объект. В тестах используйте Mock-объекты, для разрешения этой завивисимости.
Критерии приемки:

Реализован тест, который проверяет, что при выполнении Execute класса RegisterIoCDependencyMoveCommand зависимость разрешается.

**Comment by blackfyz00** [comment]
Ярослав
