### ISSUE TITLE
Регистрация зависимости Commands.Rotate в IoC

### ISSUE THREAD

**Issue by coloures** [coloures/SpaceBattleGameWithTests#25]
Зарегистрировать зависимость "Commands.Rotate" в IoC, с помощью которой можно разрешить команду MoveCommand по игровому объекту. Для регистрации зависимости определит отдельную команду с префиксом RegisterIoCDependency.
Примечание: Для того, чтобы создать RotateCommand, необходимо создать адаптер IDictionary<string, object> для интерфейса IRotatingObject. Задача конструирования Адаптеров по интерфейсу будет рассмотрена в другой лабораторной работе, поэтому в данной задаче используйте разрешение зависимости Ioc.Resolve("Adapters.IRotatingObject", obj), где obj - игровой объект. В тестах используйте Mock-объекты, для разрешения этой завивимости.
Критерии приемки:

Реализован тест, который проверяет, что при выполнении Execute класса RegisterIoCDependencyRotateCommand зависимость разрешается.

**Comment by blackfyz00** [comment]
Влад
