### ISSUE TITLE
Определить зависимость "Actions.Stop" для запуска длительной операции

### ISSUE THREAD

**Issue by coloures** [coloures/SpaceBattleGameWithTests#36]
Необходимо так определить завивисимость, чтобы следующий код позволял получать команду:

C#
IDictionary<string, object> order = ...; // приказ об остановке длительной операции
Ioc.Reolve<ICommand>("Actions.Stop", order);
Сама регистрация зависимости должна быть выполнена в команде RegisterIoCDepenedncyActionsStop

public class RegisterIoCDependencyActionsStop : ICommand
{
    public void Execute()
  {
    // здесь кодж для регистрации зависимостей
  }
}
Критерии приемки:

Реализован тест, который проверяет, что при выполнении Execute класса RegisterIoCDependencyActionsStop зависимость разрешается.
Остановка команды выполняется за константное время.

**Comment by 9vanilla9** [comment]
Макс
